### ISSUE TITLE
float16 arithmetic operations

### ISSUE THREAD

**Issue by koki0702** [MatthieuCourbariaux/deep-learning-storage#1]
Does float16 (and fixed16) format **simulate** the precision  while working with float32?
I mean, all arithmetic operations are actually carried out in float32?
If it's true I think this evaluation  is not precisely correct.

https://github.com/MatthieuCourbariaux/deep-learning-multipliers/blob/master/format.py#L44-L50

**Comment by MatthieuCourbariaux** [comment]
The precision of a fixed point multiplication actually is the precision of its operands (i.e. its inputs). 
In our code, we reduce the precision of the operands before each multiplication (realized in our case by a float32 multiplier), and thus, in my opinion, we actually perform low precision multiplications.

That being said, I am not so sure about the float16 case.

**Comment by koki0702** [comment]
Thank you for replying!

I understand what you are doing.
First you reduce the precision of the operand (e.g. from float32 to fixed16) and, after that multiply the operand by the float32 multiplier.

I mistakenly assume that you use fixed 16 not only for storing data, but also for arithmetic operation (multiplication).
